### ISSUE TITLE
Use of RepoGroup::singleton was deprecated in MediaWiki 1.34

### ISSUE THREAD

**Issue by Nikerabbit** [ProfessionalWiki/Maps#656]
### Setup

- Maps version: 7.20.1
- MW version: 1.37.0-alpha
- PHP version: 7.3.27
- SMW version (if applicable): 4.0.0-alpha

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
PHP Deprecated:  Use of RepoGroup::singleton was deprecated in MediaWiki 1.34. [Called from Maps\MapsFactory::getRepoGroup in /home/developer/mediawiki/workdir/extensions/Maps/src/MapsFactory.php at line 269] in /home/developer/mediawiki/workdir/includes/debug/MWDebug.php on line 376
```

I know 7.20.1 does not support 1.37.0-alpha, but this issue seems present in 8.x too.

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Happens on every page view for me.

**Comment by JeroenDeDauw** [comment]
@Nikerabbit would be cool if you could give v9 a spin and see if all is fluff

**Comment by Nikerabbit** [comment]
Unfortunately I cannot test it because it depends on PHP 7.4. We are still stuck on PHP 7.3.

**Comment by kghbln** [comment]
Would have been nice to get the fix in v8. Tough titties! :D
