### ISSUE TITLE
Is it possible to load MapService modules without a triggering tag?

### ISSUE THREAD

**Issue by slifty** [ProfessionalWiki/Maps#666]
I'm using an extension that does some template pre-processing, which means that my `<display_map>` tag gets processed separately from the main MediaWiki rendering flow.

Unfortunately, this means that the various hooks defined in [DisplayMapFunction.php](https://github.com/ProfessionalWiki/Maps/blob/114b1da2a09edf7ef92358c158350e390b904617/src/Map/DisplayMap/DisplayMapFunction.php#L70) don't get called; and as an result the various head modules defined in [LeafletService.php](https://github.com/ProfessionalWiki/Maps/blob/114b1da2a09edf7ef92358c158350e390b904617/src/LeafletService.php#L158-L184) are not loaded.

This renders as a loading screen

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/208884/133489262-27109640-dd41-4113-8e2d-5a06925b4f28.png">

^ the DOM has all the information, it's just that the javascript doesn't run to process it.  Indeed if I add a map tag directly in the wiki text, those hooks are triggered and both maps render properly.

I appreciate if this isn't possible or is otherwise out of scope, but wanted to check in case it is somehow supported and I missed it.

**Comment by JeroenDeDauw** [comment]
You can add the modules yourself I guess? There is no special support for this case.

**Comment by slifty** [comment]
Thanks -- and I appreciate the suggestion!
