### ISSUE TITLE
MWException: Error: invalid magic word 'leaflet' Backtrace

### ISSUE THREAD

**Issue by kaffeeringe** [ProfessionalWiki/Maps#675]
### Setup

- Maps version: 9.0.0
- MW version: 1.37
- PHP version: 7.4
- SMW version (if applicable): -

### Issue
I ran Maps 7.x on 1.34.1 and it worked fine. Now I updated both and I get this error:

> Original exception: [YbiRS17LU1LfpLNWJq4dHAAACRE] /wiki/Hilfe:Neuigkeiten MWException: Error: invalid magic word 'leaflet'
> Backtrace:
> from PATH/mediawiki-1.37.0/includes/MagicWord.php(129)
> line0 PATH/mediawiki-1.37.0/includes/MagicWordFactory.php(230): MagicWord->load(string)
> line1 PATH/mediawiki-1.37.0/includes/parser/Parser.php(4946): MagicWordFactory->get(string)
> line2 PATH/mediawiki-1.37.0/extensions/Maps/src/ParserHookSetup.php(49): Parser->setFunctionHook(string, Closure, integer)
> line3 PATH/mediawiki-1.37.0/extensions/Maps/src/ParserHookSetup.php(29): Maps\ParserHookSetup->registerServiceSpecificFunction(string, string)
> line4 PATH/mediawiki-1.37.0/extensions/Maps/src/MapsSetup.php(70): Maps\ParserHookSetup->registerParserHooks()
> line5 PATH/mediawiki-1.37.0/includes/HookContainer/HookContainer.php(338): Maps\MapsSetup->Maps\{closure}(Parser)
> line6 PATH/mediawiki-1.37.0/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
> line7 PATH/mediawiki-1.37.0/includes/HookContainer/HookRunner.php(2889): MediaWiki\HookContainer\HookContainer->run(string, array)
> line8 PATH/mediawiki-1.37.0/includes/parser/Parser.php(489): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
> line9 PATH/mediawiki-1.37.0/includes/parser/ParserFactory.php(189): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, Language, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer, MediaWiki\Tidy\RemexDriver, WANObjectCache, MediaWiki\User\UserOptionsManager, MediaWiki\User\UserFactory, MediaWikiTitleCodec, MediaWiki\Http\HttpRequestFactory)
> line10 PATH/mediawiki-1.37.0/includes/ServiceWiring.php(1117): ParserFactory->create()
> line11 PATH/mediawiki-1.37.0/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}(MediaWiki\MediaWikiServices)
> line12 PATH/mediawiki-1.37.0/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
> line13 PATH/mediawiki-1.37.0/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService(string)
> line14 PATH/mediawiki-1.37.0/includes/MediaWikiServices.php(1287): MediaWiki\MediaWikiServices->getService(string)
> line15 PATH/mediawiki-1.37.0/includes/cache/MessageCache.php(1273): MediaWiki\MediaWikiServices->getParser()
> line16 PATH/mediawiki-1.37.0/includes/cache/MessageCache.php(1252): MessageCache->getParser()
> line17 PATH/mediawiki-1.37.0/includes/language/Message.php(1362): MessageCache->transform(string, boolean, Language, Title)
> line18 PATH/mediawiki-1.37.0/includes/language/Message.php(935): Message->transformText(string)
> line19 PATH/mediawiki-1.37.0/includes/language/Message.php(993): Message->format(string)
> line20 PATH/mediawiki-1.37.0/includes/OutputPage.php(944): Message->text()
> line21 PATH/mediawiki-1.37.0/includes/OutputPage.php(993): OutputPage->setHTMLTitle(Message)
> line22 PATH/mediawiki-1.37.0/includes/page/Article.php(464): OutputPage->setPageTitle(string)
> line23 PATH/mediawiki-1.37.0/includes/actions/ViewAction.php(74): Article->view()
> line24 PATH/mediawiki-1.37.0/includes/MediaWiki.php(538): ViewAction->show()
> line25 PATH/mediawiki-1.37.0/includes/MediaWiki.php(320): MediaWiki->performAction(Article, Title)
> line26 PATH/mediawiki-1.37.0/includes/MediaWiki.php(925): MediaWiki->performRequest()
> line27 PATH/mediawiki-1.37.0/includes/MediaWiki.php(559): MediaWiki->main()
> line28 PATH/mediawiki-1.37.0/index.php(53): MediaWiki->run()
> line29 PATH/mediawiki-1.37.0/index.php(46): wfIndexMain()
> line30 {main}

**Comment by JeroenDeDauw** [comment]
Cannot reproduce using the same version of MediaWiki.

Perhaps you have a broken extension loaded that makes Maps fail.

**Comment by kaffeeringe** [comment]
Well, it works with the older version of Maps. display_errors shows only some warnings for deprecated variables and functions.

I installed the tarball from Github. Is there a difference to installing it via Composer?

**Comment by kaffeeringe** [comment]
I disabled all other extensions. The error still occours. I'll try and reupload Mediawiki.

**Comment by kaffeeringe** [comment]
Ok. I downloaded Maps via composer and it works. It would be cool, if there also was a tarball-release.
