### ISSUE TITLE
With Maps enabled, /maintenance/update.php is not running

### ISSUE THREAD

**Issue by wanjaus** [ProfessionalWiki/Maps#680]
### Setup

- Maps version: 9.0.1
- MW version: 1.37.1
- PHP version: 8.0.14
- SMW version (if applicable): 

### Issue
With Maps enabled, /maintenance/update.php is not running and any other scripts under /maintenance/. It produces the error below;
 Error: Maps\MapsSetup::__construct(): Argument #1 ($mwGlobals) cannot be passed by reference

Backtrace:

from /var/lib/mediawiki/extensions/Maps/MapsRegistration.php(48)

#0 /var/lib/mediawiki/includes/Setup.php(856): MapsRegistration::{closure}()

1 /var/lib/mediawiki/maintenance/doMaintenance.php(90): require_once(string)

2 /var/lib/mediawiki/maintenance/update.php(264): require_once(string)

3 {main}
Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by wanjaus** [comment]
> ### Setup
> 
>     * Maps version: 9.0.1
> 
>     * MW version: 1.37.1
> 
>     * PHP version: 8.0.14
> 
>     * SMW version (if applicable):
> 
> 
> ### Issue
> 
> With Maps enabled, /maintenance/update.php is not running and any other scripts under /maintenance/. It produces the error below; Error: Maps\MapsSetup::__construct(): Argument #1 ($mwGlobals) cannot be passed by reference
> 
> Backtrace:
> 
> from /var/lib/mediawiki/extensions/Maps/MapsRegistration.php(48)
> 
> #0 /var/lib/mediawiki/includes/Setup.php(856): MapsRegistration::{closure}()
> 
> 1 /var/lib/mediawiki/maintenance/doMaintenance.php(90): require_once(string)
> 
> 2 /var/lib/mediawiki/maintenance/update.php(264): require_once(string)
> 
> 3 {main} Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:
> 
> Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by Sai05091990** [comment]
I am also seeing similar issue after adding Mpas to extenions folder and enabled in localsettings.php , run the update.php is giving error:

PHP Fatal error:  Uncaught UnexpectedValueException: callback 'MapsRegistration::onRegistration' is not callable in /opt/bitnami/mediawiki/include
s/registration/ExtensionRegistry.php:544
Stack trace:
#0 /opt/bitnami/mediawiki/includes/registration/ExtensionRegistry.php(231): ExtensionRegistry->exportExtractedData()
#1 /opt/bitnami/mediawiki/includes/Setup.php(168): ExtensionRegistry->loadFromQueue()
#2 /opt/bitnami/mediawiki/maintenance/doMaintenance.php(90): require_once('/opt/bitnami/me...')
#3 /opt/bitnami/mediawiki/maintenance/update.php(264): require_once('/opt/bitnami/me...')
#4 {main}
  thrown in /opt/bitnami/mediawiki/includes/registration/ExtensionRegistry.php on line 544
I have no name!@mediawiki-6b86ff6864-n8xvr:/$

**Comment by JeroenDeDauw** [comment]
The original issue you reported:

> Error: Maps\MapsSetup::__construct(): Argument https://github.com/ProfessionalWiki/Maps/pull/1 ($mwGlobals) cannot be passed by reference

was fixed in Maps 9.0.5.

The error in your most recent comment suggests something is wrong installation wise on your wiki, not in Maps itself.

**Comment by Sai05091990** [comment]
i was successfully able to add other extensions but only Maps is giving issue.

**Comment by JeroenDeDauw** [comment]
How did you install Maps? With Composer? As indicated here? https://maps.extension.wiki/wiki/Installation

**Comment by Sai05091990** [comment]
Not with composer. 

I have downloaded the Maps extensions manually and moved the complete Maps folder to root folder /opt/bitnami/mediawiki/extensions/

and then updated my Localsettings.php

then my pod started giving me the reported error.

**Comment by JeroenDeDauw** [comment]
Well yes. Maps needs to be installed with Composer. Else the dependencies and class loading are not there.
