### ISSUE TITLE
Syntax Highlighter tag not working on https://maps.extension.wiki/wiki/Installation

### ISSUE THREAD

**Issue by wanjaus** [ProfessionalWiki/Maps#681]
A small issue I noticed on the website where `<syntaxhighlight></syntaxhighlight>` is not working. Tried on Edge, MS Edge and Firefox.

![image](https://user-images.githubusercontent.com/98474886/153561262-63aa1116-cacd-4d8b-bad9-5d86ad0317fa.png)

**Comment by JeroenDeDauw** [comment]
Oops :) Thank you for notifying us. Fixed now.
