### ISSUE TITLE
Error with MediaWiki on Synology DSM 7.1

### ISSUE THREAD

**Issue by drewdsaur** [ProfessionalWiki/Maps#692]
I am getting the following when I visit my Wiki after installation. What might I be doing wrong? First time I have experienced this issue after years of use.

`Fatal error: Uncaught UnexpectedValueException: callback 'MapsRegistration::onRegistration' is not callable in /volume1/web_packages/mediawiki/includes/registration/ExtensionRegistry.php on line 548 UnexpectedValueException: callback 'MapsRegistration::onRegistration' is not callable in /volume1/web_packages/mediawiki/includes/registration/ExtensionRegistry.php on line 548 Call Stack: 0.0001 367488 1. {main}() /volume1/web_packages/mediawiki/index.php:0 0.0003 367960 2. require('/volume1/web_packages/mediawiki/includes/WebStart.php') /volume1/web_packages/mediawiki/index.php:44 0.0003 380040 3. require_once('/volume1/web_packages/mediawiki/includes/Setup.php') /volume1/web_packages/mediawiki/includes/WebStart.php:89 0.0033 466032 4. ExtensionRegistry->loadFromQueue() /volume1/web_packages/mediawiki/includes/Setup.php:161 0.0045 677808 5. ExtensionRegistry->exportExtractedData($info = ['globals' => ['wgExtensionMessagesFiles' => [...], 'wgMessagesDirs' => [...], 'wgHooks' => [...], 'wgValidSkinNames' => [...], 'wgDefaultUserOptions' => [...], 'wgTimelessBackdropImage' => 'cat.svg', 'wgTimelessLogo' => NULL, 'wgTimelessWordmark' => NULL, 'wgServiceWiringFiles' => [...], 'wgVectorUseIconWatch' => TRUE, 'wgVectorResponsive' => FALSE, 'wgVectorShowSkinPreferences' => TRUE, 'wgVectorDefaultSkinVersion' => '1', 'wgVectorDefaultSkinVersionForExistingAccounts' => '1', 'wgVectorDefaultSkinVersionForNewAccounts' => '1', 'wgVectorDefaultSidebarVisibleForAuthorisedUser' => TRUE, 'wgVectorDefaultSidebarVisibleForAnonymousUser' => FALSE, 'wgVectorLayoutMaxWidth' => FALSE, 'wgConfigRegistry' => [...], 'wgContentNamespaces' => [...], 'wgNamespaceContentModels' => [...], 'wgNamespacesWithSubpages' => [...], 'wgContentHandlers' => [...], 'wgCSSPath' => FALSE, 'wgCSSIdentifier' => 'css-extension', 'wgAutoloadClasses' => [...]], 'config' => ['TimelessBackdropImage' => [...], 'TimelessLogo' => [...], 'TimelessWordmark' => [...], 'VectorUseIconWatch' => [...], 'VectorResponsive' => [...], 'VectorShowSkinPreferences' => [...], 'VectorDefaultSkinVersion' => [...], 'VectorDefaultSkinVersionForExistingAccounts' => [...], 'VectorDefaultSkinVersionForNewAccounts' => [...], 'VectorDefaultSidebarVisibleForAuthorisedUser' => [...], 'VectorDefaultSidebarVisibleForAnonymousUser' => [...], 'VectorLayoutMaxWidth' => [...]], 'defines' => ['NS_GEO_JSON' => 420, 'NS_GEO_JSON_TALK' => 421], 'callbacks' => ['Maps' => 'MapsRegistration::onRegistration'], 'credits' => ['MonoBook' => [...], 'Timeless' => [...], 'Vector' => [...], 'Maps' => [...], 'CSS' => [...]], 'attributes' => ['ResourceModules' => [...], 'ResourceModuleSkinStyles' => [...], 'SkinOOUIThemes' => [...], 'ExtensionNamespaces' => [...]], 'warnings' => FALSE, 'autoloaderPaths' => [0 => '/volume1/web_packages/mediawiki/extensions/Maps/vendor/autoload.php'], 'autoloaderNS' => ['Vector\' => '/volume1/web_packages/mediawiki/skins/Vector/includes/']]) /volume1/web_packages/mediawiki/includes/registration/ExtensionRegistry.php:234`

**Comment by JeroenDeDauw** [comment]
What version of MediaWiki and what version of Maps?

**Comment by drewdsaur** [comment]
1.35 and 9.0

--
Drew D. Saur
Adjunct Faculty
RIT Department of Software Engineering
585-281-0014 (cell)
https://www.rit.edu/computing/directory/ddsvse-drew-saur

On May 4, 2022, at 1:10 PM, Jeroen De Dauw ***@***.******@***.***>> wrote:



What version of MediaWiki and what version of Maps?

**Comment by JeroenDeDauw** [comment]
Try using the latest version of Maps: 9.0.7

Another thing to double check is if you ran Composer. If you install Maps without composer, you will get an error like that.

**Comment by drewdsaur** [comment]
I am so grateful for you reaching out.

I did run composer. The weird thing is that if I run the composer update in the mediawiki directory (sudo php74 ./composer.phar update) it messes up the composer install in the mediawiki/vendor directory. I figured things out so that I got it to a point where I run sudo php74 ./composer.phar update in the mediawiki/vendor directory last, then just run sudo php74 ./composer.phar update mediawiki/maps --no-dev -o in the mediawiki directory, it seems to settle things.

I just executed

sudo COMPOSER=composer.local.json php74 ./composer.phar require --no-update mediawiki/maps:~9.0.7

and

sudo php74 ./composer.phar update mediawiki/maps --no-dev -o

….in the mediawiki directory and with the Maps extension *disabled*, I wind up getting the below.

The only thing that fixes that is to run sudo php74 ./composer.phar update in the mediawiki/vendor directory, which enables me to run MediaWiki just fine with the Maps extension disabled. But if I un comment # wfLoadExtension( 'Maps' ); in LocalSettings.php, I am back to square one with the message I shared.


Warning: require(/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php): failed to open stream: Permission denied in /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php on line 75 Call Stack: 0.0001 367488 1. {main}() /volume1/web_packages/mediawiki/index.php:0 0.0002 367960 2. require('/volume1/web_packages/mediawiki/includes/WebStart.php') /volume1/web_packages/mediawiki/index.php:44 0.0003 380040 3. require_once('/volume1/web_packages/mediawiki/includes/Setup.php') /volume1/web_packages/mediawiki/includes/WebStart.php:89 0.0012 459328 4. require_once('/volume1/web_packages/mediawiki/vendor/autoload.php') /volume1/web_packages/mediawiki/includes/Setup.php:107 0.0016 460032 5. ComposerAutoloaderInit_mediawiki_vendor::getLoader() /volume1/web_packages/mediawiki/vendor/autoload.php:7 0.0081 464744 6. composerRequire_mediawiki_vendor($fileIdentifier = 'af3cc937b8a54e5b4209c82d6cfe8889', $file = '/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php') /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php:65 Fatal error: require(): Failed opening required '/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php' (include_path='/volume1/web_packages/mediawiki/vendor/pear/console_getopt:/volume1/web_packages/mediawiki/vendor/pear/mail:/volume1/web_packages/mediawiki/vendor/pear/mail_mime:/volume1/web_packages/mediawiki/vendor/pear/net_smtp:/volume1/web_packages/mediawiki/vendor/pear/net_socket:/volume1/web_packages/mediawiki/vendor/pear/pear-core-minimal/src:/volume1/web_packages/mediawiki/vendor/pear/pear_exception:.:/usr/share/pear') in /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php on line 75 Call Stack: 0.0001 367488 1. {main}() /volume1/web_packages/mediawiki/index.php:0 0.0002 367960 2. require('/volume1/web_packages/mediawiki/includes/WebStart.php') /volume1/web_packages/mediawiki/index.php:44 0.0003 380040 3. require_once('/volume1/web_packages/mediawiki/includes/Setup.php') /volume1/web_packages/mediawiki/includes/WebStart.php:89 0.0012 459328 4. require_once('/volume1/web_packages/mediawiki/vendor/autoload.php') /volume1/web_packages/mediawiki/includes/Setup.php:107 0.0016 460032 5. ComposerAutoloaderInit_mediawiki_vendor::getLoader() /volume1/web_packages/mediawiki/vendor/autoload.php:7 0.0081 464744 6. composerRequire_mediawiki_vendor($fileIdentifier = 'af3cc937b8a54e5b4209c82d6cfe8889', $file = '/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php') /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php:65


--
Drew D. Saur
Adjunct Faculty
RIT Department of Software Engineering
585-281-0014 (cell)
https://www.rit.edu/computing/directory/ddsvse-drew-saur

On May 4, 2022, at 1:27 PM, Jeroen De Dauw ***@***.******@***.***>> wrote:



Try using the latest version of Maps: 9.0.7

Another thing to double check is if you ran Composer. If you install Maps without composer, you will get an error like that.

**Comment by JeroenDeDauw** [comment]
Try running `composer update` in the mediawiki root.

Running with sudo might cause problems btw. If the files installed via composer are not readable by your webserver/php, then things will not work.

**Comment by drewdsaur** [comment]
I’ve always had to run composer as root in the Synology DSM environment. It’s always been successful before.

When I *don’t*,  I get messages like this:

```
zellmin@Files:/volume1/web_packages/mediawiki$ php74 ./composer.phar update
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 88 installs, 5 updates, 0 removals
    Failed to download composer/package-versions-deprecated from dist: /volume1/web_packages/mediawiki/vendor/composer/package-versions-deprecated does not exist and could not be created.
    Now trying to download from source

                                                            
  [RuntimeException]                                        
  git was not found in your PATH, skipping source download  
                                                            

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

…back to running `sudo php74 ./composer.phar update:`

```
zellmin@Files:/volume1/web_packages/mediawiki$ sudo php74 ./composer.phar update
Password: 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 87 installs, 5 updates, 5 removals
  - Removing swaggest/json-schema (v0.12.29)
  - Removing swaggest/json-diff (v3.8.3)
  - Removing phplang/scope-exit (1.0.0)
  - Removing jakobo/hotp-php (v2.0.0)
  - Removing christian-riesen/base32 (1.4.0)
  - Installing composer/package-versions-deprecated (1.11.99.5): Extracting archive
  - Installing composer/installers (v2.1.1): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
  - Installing doctrine/cache (1.12.1): Extracting archive
  - Installing doctrine/dbal (3.0.0): Extracting archive
  - Installing doctrine/sql-formatter (1.1.0): Extracting archive
  - Installing giorgiosironi/eris (0.10.0): Extracting archive
  - Installing symfony/polyfill-php72 (v1.25.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-intl-idn (v1.17.0 => v1.25.0): Extracting archive
  - Upgrading guzzlehttp/psr7 (1.7.0 => 1.8.5): Extracting archive
  - Upgrading guzzlehttp/promises (1.4.0 => 1.5.1): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/type (1.1.4): Extracting archive
  - Installing sebastian/resource-operations (2.0.2): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/global-state (3.0.2): Extracting archive
  - Installing sebastian/exporter (3.1.4): Extracting archive
  - Installing sebastian/environment (4.2.4): Extracting archive
  - Installing sebastian/diff (3.0.3): Extracting archive
  - Installing sebastian/comparator (3.0.3): Extracting archive
  - Installing phpunit/php-timer (2.1.3): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (2.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-token-stream (4.0.4): Extracting archive
  - Installing phpunit/php-code-coverage (7.0.15): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.6.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing doctrine/instantiator (1.4.1): Extracting archive
  - Installing phpspec/prophecy (v1.15.0): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.0): Extracting archive
  - Installing phpunit/phpunit (8.5.26): Extracting archive
  - Installing johnkary/phpunit-speedtrap (v3.3.0): Extracting archive
  - Installing justinrainbow/json-schema (5.2.12): Extracting archive
  - Installing data-values/interfaces (1.0.0): Extracting archive
  - Installing data-values/data-values (3.0.0): Extracting archive
  - Installing data-values/validators (1.0.0): Extracting archive
  - Installing data-values/common (1.0.0): Extracting archive
  - Installing param-processor/param-processor (1.12.0): Extracting archive
  - Installing mediawiki/validator (2.2.3): Extracting archive
  - Installing mediawiki/parser-hooks (1.6.1): Extracting archive
  - Installing jmikola/geojson (1.0.3): Extracting archive
  - Installing willdurand/geocoder (4.5.0): Extracting archive
  - Installing jeroen/file-fetcher (6.1.0): Extracting archive
  - Installing data-values/geo (4.3.0): Extracting archive
  - Installing jeroen/simple-geocoder (1.3.1): Extracting archive
  - Installing jeroen/simple-cache (2.0.0): Extracting archive
  - Installing psr/simple-cache (1.0.1): Extracting archive
  - Installing jeroen/file-fetcher-cache (1.0.1): Extracting archive
  - Installing mediawiki/maps (9.0.7): Extracting archive
  - Installing squizlabs/php_codesniffer (3.5.8): Extracting archive
  - Installing composer/spdx-licenses (1.5.3): Extracting archive
  - Installing mediawiki/mediawiki-codesniffer (v34.0.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.25.0): Extracting archive
  - Installing symfony/string (v5.4.8): Extracting archive
  - Installing symfony/service-contracts (v2.2.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.25.0): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.1): Extracting archive
  - Installing symfony/console (v5.4.8): Extracting archive
  - Installing sabre/event (5.1.4): Extracting archive
  - Installing netresearch/jsonmapper (v3.1.1): Extracting archive
  - Installing microsoft/tolerant-php-parser (v0.0.23): Extracting archive
  - Installing felixfbecker/advanced-json-rpc (v3.2.1): Extracting archive
  - Installing composer/xdebug-handler (1.4.6): Extracting archive
  - Installing phan/phan (3.2.6): Extracting archive
  - Installing mediawiki/phan-taint-check-plugin (3.2.1): Extracting archive
  - Installing mediawiki/mediawiki-phan-config (0.10.6): Extracting archive
  - Installing monolog/monolog (2.2.0): Extracting archive
  - Installing nmred/kafka-php (v0.1.5): Extracting archive
  - Installing php-parallel-lint/php-console-color (v0.3): Extracting archive
  - Installing php-parallel-lint/php-console-highlighter (v0.5): Extracting archive
  - Installing pimple/pimple (v3.3.1): Extracting archive
  - Installing symfony/var-dumper (v5.4.8): Extracting archive
  - Installing nikic/php-parser (v4.4.0): Extracting archive
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Extracting archive
  - Installing psy/psysh (v0.10.4): Extracting archive
  - Installing seld/jsonlint (1.8.3): Extracting archive
  - Installing symfony/yaml (v5.0.11): Extracting archive
  - Installing wikimedia/avro (v1.9.0): Extracting archive
  - Upgrading wikimedia/zest-css (1.1.3 => 1.1.5): Extracting archive
  - Upgrading wikimedia/wikipeg (2.0.5 => 2.0.6): Extracting archive
  - Installing wikimedia/testing-access-wrapper (2.0.0): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing wmde/hamcrest-html-matchers (v0.1.1): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
50 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> ComposerVendorHtaccessCreator::onEvent
```

…then visiting my Wiki, I get this in the web browser:

Warning: require(/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php): failed to open stream: Permission denied in /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php on line 75 Call Stack: 0.0001 367488 1. {main}() /volume1/web_packages/mediawiki/index.php:0 0.0002 367960 2. require('/volume1/web_packages/mediawiki/includes/WebStart.php') /volume1/web_packages/mediawiki/index.php:44 0.0003 380040 3. require_once('/volume1/web_packages/mediawiki/includes/Setup.php') /volume1/web_packages/mediawiki/includes/WebStart.php:89 0.0012 459328 4. require_once('/volume1/web_packages/mediawiki/vendor/autoload.php') /volume1/web_packages/mediawiki/includes/Setup.php:107 0.0016 460032 5. ComposerAutoloaderInit_mediawiki_vendor::getLoader() /volume1/web_packages/mediawiki/vendor/autoload.php:7 0.0081 464744 6. composerRequire_mediawiki_vendor($fileIdentifier = 'af3cc937b8a54e5b4209c82d6cfe8889', $file = '/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php') /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php:65 Fatal error: require(): Failed opening required '/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php' (include_path='/volume1/web_packages/mediawiki/vendor/pear/console_getopt:/volume1/web_packages/mediawiki/vendor/pear/mail:/volume1/web_packages/mediawiki/vendor/pear/mail_mime:/volume1/web_packages/mediawiki/vendor/pear/net_smtp:/volume1/web_packages/mediawiki/vendor/pear/net_socket:/volume1/web_packages/mediawiki/vendor/pear/pear-core-minimal/src:/volume1/web_packages/mediawiki/vendor/pear/pear_exception:.:/usr/share/pear') in /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php on line 75 Call Stack: 0.0001 367488 1. {main}() /volume1/web_packages/mediawiki/index.php:0 0.0002 367960 2. require('/volume1/web_packages/mediawiki/includes/WebStart.php') /volume1/web_packages/mediawiki/index.php:44 0.0003 380040 3. require_once('/volume1/web_packages/mediawiki/includes/Setup.php') /volume1/web_packages/mediawiki/includes/WebStart.php:89 0.0012 459328 4. require_once('/volume1/web_packages/mediawiki/vendor/autoload.php') /volume1/web_packages/mediawiki/includes/Setup.php:107 0.0016 460032 5. ComposerAutoloaderInit_mediawiki_vendor::getLoader() /volume1/web_packages/mediawiki/vendor/autoload.php:7 0.0081 464744 6. composerRequire_mediawiki_vendor($fileIdentifier = 'af3cc937b8a54e5b4209c82d6cfe8889', $file = '/volume1/web_packages/mediawiki/vendor/composer/../param-processor/param-processor/DefaultConfig.php') /volume1/web_packages/mediawiki/vendor/composer/autoload_real.php:65

Then run composer update in the vendor/ directory:

```
zellmin@Files:/volume1/web_packages/mediawiki$ cd vendor/
zellmin@Files:/volume1/web_packages/mediawiki/vendor$ sudo php74 ./composer.phar update
Password: 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Loading composer repositories with package information
Info from [https://repo.packagist.org:](https://repo.packagist.org/) #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 5 installs, 5 updates, 85 removals
  - Removing wmde/hamcrest-html-matchers (v0.1.1)
  - Removing willdurand/geocoder (4.5.0)
  - Removing wikimedia/testing-access-wrapper (2.0.0)
  - Removing wikimedia/avro (v1.9.0)
  - Removing webmozart/assert (1.10.0)
  - Removing theseer/tokenizer (1.2.1)
  - Removing symfony/yaml (v5.0.11)
  - Removing symfony/var-dumper (v5.4.8)
  - Removing symfony/string (v5.4.8)
  - Removing symfony/service-contracts (v2.2.0)
  - Removing symfony/polyfill-php73 (v1.25.0)
  - Removing symfony/polyfill-php72 (v1.25.0)
  - Removing symfony/polyfill-intl-normalizer (v1.25.0)
  - Removing symfony/polyfill-intl-grapheme (v1.25.0)
  - Removing symfony/deprecation-contracts (v2.5.1)
  - Removing symfony/console (v5.4.8)
  - Removing squizlabs/php_codesniffer (3.5.8)
  - Removing seld/jsonlint (1.8.3)
  - Removing sebastian/version (2.0.1)
  - Removing sebastian/type (1.1.4)
  - Removing sebastian/resource-operations (2.0.2)
  - Removing sebastian/recursion-context (3.0.1)
  - Removing sebastian/object-reflector (1.1.2)
  - Removing sebastian/object-enumerator (3.0.4)
  - Removing sebastian/global-state (3.0.2)
  - Removing sebastian/exporter (3.1.4)
  - Removing sebastian/environment (4.2.4)
  - Removing sebastian/diff (3.0.3)
  - Removing sebastian/comparator (3.0.3)
  - Removing sebastian/code-unit-reverse-lookup (1.0.2)
  - Removing sabre/event (5.1.4)
  - Removing psy/psysh (v0.10.4)
  - Removing psr/simple-cache (1.0.1)
  - Removing pimple/pimple (v3.3.1)
  - Removing phpunit/phpunit (8.5.26)
  - Removing phpunit/php-token-stream (4.0.4)
  - Removing phpunit/php-timer (2.1.3)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing phpunit/php-file-iterator (2.0.5)
  - Removing phpunit/php-code-coverage (7.0.15)
  - Removing phpspec/prophecy (v1.15.0)
  - Removing phpdocumentor/type-resolver (1.6.1)
  - Removing phpdocumentor/reflection-docblock (5.3.0)
  - Removing phpdocumentor/reflection-common (2.2.0)
  - Removing php-parallel-lint/php-console-highlighter (v0.5)
  - Removing php-parallel-lint/php-console-color (v0.3)
  - Removing phar-io/version (3.2.1)
  - Removing phar-io/manifest (2.0.3)
  - Removing phan/phan (3.2.6)
  - Removing param-processor/param-processor (1.12.0)
  - Removing nmred/kafka-php (v0.1.5)
  - Removing nikic/php-parser (v4.4.0)
  - Removing netresearch/jsonmapper (v3.1.1)
  - Removing myclabs/deep-copy (1.11.0)
  - Removing monolog/monolog (2.2.0)
  - Removing microsoft/tolerant-php-parser (v0.0.23)
  - Removing mediawiki/phan-taint-check-plugin (3.2.1)
  - Removing mediawiki/parser-hooks (1.6.1)
  - Removing mediawiki/mediawiki-phan-config (0.10.6)
  - Removing mediawiki/mediawiki-codesniffer (v34.0.0)
  - Removing justinrainbow/json-schema (5.2.12)
  - Removing johnkary/phpunit-speedtrap (v3.3.0)
  - Removing jmikola/geojson (1.0.3)
  - Removing jeroen/simple-geocoder (1.3.1)
  - Removing jeroen/simple-cache (2.0.0)
  - Removing jeroen/file-fetcher-cache (1.0.1)
  - Removing jeroen/file-fetcher (6.1.0)
  - Removing hamcrest/hamcrest-php (v2.0.1)
  - Removing giorgiosironi/eris (0.10.0)
  - Removing felixfbecker/advanced-json-rpc (v3.2.1)
  - Removing doctrine/sql-formatter (1.1.0)
  - Removing doctrine/instantiator (1.4.1)
  - Removing doctrine/event-manager (1.1.1)
  - Removing doctrine/dbal (3.0.0)
  - Removing doctrine/cache (1.12.1)
  - Removing dnoegel/php-xdg-base-dir (v0.1.1)
  - Removing data-values/validators (1.0.0)
  - Removing data-values/interfaces (1.0.0)
  - Removing data-values/geo (4.3.0)
  - Removing data-values/data-values (3.0.0)
  - Removing data-values/common (1.0.0)
  - Removing composer/xdebug-handler (1.4.6)
  - Removing composer/spdx-licenses (1.5.3)
  - Removing composer/package-versions-deprecated (1.11.99.5)
  - Removing composer/installers (v2.1.1)
  - Installing christian-riesen/base32 (1.4.0): Extracting archive
    Unzipping using 7z 16.02 may result in incorrect file permissions. Install 7z 21.01+ or unzip to ensure you get correct permissions.
  - Downgrading symfony/polyfill-intl-idn (v1.25.0 => v1.17.0): Extracting archive
  - Downgrading guzzlehttp/psr7 (1.8.5 => 1.7.0): Extracting archive
  - Downgrading guzzlehttp/promises (1.5.1 => 1.4.0): Extracting archive
  - Installing jakobo/hotp-php (v2.0.0): Extracting archive
  - Installing swaggest/json-diff (v3.8.3): Extracting archive
  - Installing phplang/scope-exit (1.0.0): Extracting archive
  - Installing swaggest/json-schema (v0.12.29): Extracting archive
  - Downgrading wikimedia/zest-css (1.1.5 => 1.1.3): Extracting archive
  - Downgrading wikimedia/wikipeg (2.0.6 => 2.0.5): Extracting archive
Generating optimized autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

This gets my MediaWiki working OK...but maps doesn’t work once I enable the extension.

I hope this helps.

Drew

**Comment by drewdsaur** [comment]
As a conclusion, I wound up restoring from a backup and all is good. Something must've gotten hosed in the transition from DSM 7.0 to 7.1.
