### ISSUE TITLE
"The '_geo' type of this property is invalid"--but Maps is already enabled

### ISSUE THREAD

**Issue by Routhwick** [ProfessionalWiki/Maps#741]
### Setup

- Maps version: 10.0.0 (4fe56fa)
- MW version: [1.39.3](https://mediawiki.org/wiki/MediaWiki_1.39) (56751eb)
- PHP version: 7.4.33 (fpm-fcgi)
- SMW version (if applicable): 4.1.1 (c5a1042)

### Issue

On [my wiki](https://constantnoble.miraheze.org), SMW and Maps are both already enabled for use in the Place namespace. However, on pages using the "Geographic coordinates" datatype (or an eponymous/similarly named semantic property), the location data generates this "Processing error" message from affected "Browse properties" pages (and also appears via the orange-warning-circle sign next to the coordinates) for whatever reason:

> ``The "_geo" type of this property is invalid``

Googling on this error led me nowhere aside from a few off-Miraheze references; amazingly, not even MediaWiki, SMW.org, GitHub, or the like have picked up on it yet. (Or in GitHub's case, not in the last eight years even [#97].) Furthermore, the "Errors" tab on [the type's own page](https://constantnoble.miraheze.org/wiki/Special:Types/Geographic_coordinates) states:

> [Extension "Maps"](https://semantic-mediawiki.org/wiki/Extension:Maps) was not detected[,] therefore "Geographic coordinates" is restricted in its capacity to operate.

Although [Special:Version](https://constantnoble.miraheze.org/wiki/Special:Version) insists otherwise. Beyond that, what exactly's holding it up?

(*Already filed at MH Phab [[T10611](https://phabricator.miraheze.org/T10611)].*)

**Comment by lucastucious** [comment]
Following, as i encouter the same issue. Issue that prevent me to do queries for coordinates and have dynamic maps.

**Comment by JeroenDeDauw** [comment]
Working fine at https://maps.extension.wiki/wiki/Leaflet_SMW_queries

**Comment by lucastucious** [comment]
It was on the Miraheze side ! maybe close this one
