### ISSUE TITLE
Working configuration SMW, Maps and PHP 8.1?

### ISSUE THREAD

**Issue by kaddigat** [ProfessionalWiki/Maps#746]
Is there a currently working configuration for the combination of SMW, Maps and PHP 8.1?

My problem is that SMW 4.1 and Maps 10.0 do not like each other,
but the installation of SMW 4.0 in combination with PHP 8.1 does not work either (https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5300)

**Comment by JeroenDeDauw** [comment]
Maps and SMW 4.1 work together as shown on the demo wiki: https://maps.extension.wiki/wiki/Special:Version

**Comment by kaddigat** [comment]
Thx. However, in the demo wiki, PHP 8.0.28 is used.
With PHP 8.1.16 MediaWiki 1.38.4, SemanticMediaWiki 4.1.1 i am getting the following error after trying to use maps with a simple command like {{#display_map:center=Brandenburg Gate, Berlin, Germany}}:

Fatal error: Declaration of MWCallbackStream::write($string) must be compatible with Psr\Http\Message\StreamInterface::write(string $string): int in /.../includes/http/MWCallbackStream.php on line 46

I will check in a minute whether the combination with MediaWiki 1.39 instead of 1.38 works better.

**Comment by JeroenDeDauw** [comment]
That is a MediaWiki issue: https://phabricator.wikimedia.org/T335073
