### ISSUE TITLE
GeoJson: pages show json instead of map as of MW 1.39

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/Maps#763]
### Issue

Since MW 1.39, pages in the GeoJson namespace show their json structure:
https://maps.extension.wiki/wiki/GeoJson:Berlin
Before that they showed the map with the GeoJson editor, which is of course the preferred solution in case of geojson data.

Is there any way to bring back the old behavior also in 1.39?

**Comment by JeroenDeDauw** [comment]
I'm not sure if @thomas-topway-it his PR at https://github.com/ProfessionalWiki/Maps/pull/767 actually fixed this issue, since https://maps.extension.wiki/wiki/GeoJson:Berlin is still showing JSON

**Comment by krabina** [comment]
Interesting. Also in my testwiki it does not work: https://test.knowledge.wiki/GeoJson:BG_Innere_Stadt

**Comment by thomas-topway-it** [comment]
@JeroenDeDauw I've installed Maps master https://github.com/ProfessionalWiki/Maps on the test wiki and it works https://test.knowledge.wiki/GeoJson:BG_Innere_Stadt -- the version here https://maps.extension.wiki/wiki/Special:Version seems not master (10.2.0)
