### ISSUE TITLE
Call to undefined addHeadItem method

### ISSUE THREAD

**Issue by Oreolek** [ProfessionalWiki/Maps#781]
### Setup

- Maps version: 10.2.0
- MW version: 1.42.1, although the bug was present on 1.41 too
- PHP version: 8.2
- Cargo version: 3.6

### Issue

```
Error: Call to undefined method MediaWiki\Parser\Parser::addHeadItem()

Backtrace:

from extensions/Maps/src/Map/CargoFormat/CargoFormat.php(38)
#0 extensions/Cargo/includes/CargoQueryDisplayer.php(398): Maps\Map\CargoFormat\CargoFormat->display()
#1 extensions/Cargo/includes/parserfunctions/CargoQuery.php(170): CargoQueryDisplayer->displayQueryResults()
```

Goes away if I disable Maps but the maps go away too :-(

**Comment by JeroenDeDauw** [comment]
I suspect [this](https://github.com/ProfessionalWiki/Maps/pull/782) fixes your issue. Would be nice if you could confirm

**Comment by Oreolek** [comment]
Yup, all works! Thank you!
